Repository OptimumPartners/reverifi, pull requests merged in 2021-12, with the labels that each got.

#12 REV-003: Featured listing
  package-lock.json
  package.json
  src/assets/icons/air-conditioner.svg
  src/assets/icons/bathtub.svg
  src/assets/icons/bedroom.svg
  src/assets/icons/bench.svg
  src/assets/icons/heart.svg
  src/assets/icons/left-arrow.svg
  src/assets/icons/location-pin.svg
  src/assets/icons/right-arrow.svg
  src/assets/icons/share.svg
  src/assets/icons/wifi.svg
  src/assets/images/apartment1.png
  src/assets/images/apartment2.png
  src/assets/images/apartment3.png
  src/assets/images/person.png
  src/components/FeaturedListing/Card/Card.jsx
  src/components/FeaturedListing/Card/Card.test.jsx
  src/components/FeaturedListing/Card/card.styles.js
  src/components/FeaturedListing/FeaturedListing.test.jsx
  src/components/FeaturedListing/__snapshots__/FeaturedListing.test.jsx.snap
  src/components/FeaturedListing/data.js
  src/components/FeaturedListing/featured-listing.styles.js
  src/components/FeaturedListing/index.jsx
  src/pages/Home.jsx
  src/setupTests.js
  src/styles/breakpoints.js
  src/styles/colors.js
  src/styles/global-styles.js
Labels: Passed Code Review

#14 REV-004: Add footer and claim address
  .eslintrc
  package.json
  setup-jest.js
  src/assets/images/arrow.svg
  src/assets/images/claim-address-desktop.svg
  src/assets/images/claim-address-mobile.svg
  src/assets/images/facebook.svg
  src/assets/images/instagram.svg
  src/assets/images/linkedin.svg
  src/assets/images/location-pin-star.svg
  src/assets/images/location-pin.svg
  src/assets/images/white-logo.svg
  src/assets/images/youtube.svg
  src/components/ClaimAddress /claim-address.styles.js
  src/components/ClaimAddress /index.jsx
  src/components/ClaimAddress/__snapshots__/claim-address.test.jsx.snap
  src/components/ClaimAddress/claim-address.styles.js
  src/components/ClaimAddress/claim-address.test.jsx
  src/components/ClaimAddress/index.jsx
  src/components/Footer/footer.styles.js
  src/components/Footer/index.jsx
  src/components/shared/Footer/SupportInfo.jsx
  src/components/shared/Footer/__snapshots__/footer.test.jsx.snap
  src/components/shared/Footer/footer.styles.js
  src/components/shared/Footer/footer.test.jsx
  src/components/shared/Footer/index.jsx
  src/components/shared/Input/Input.test.jsx
  src/components/shared/Input/__snapshots__/Input.test.jsx.snap
  src/components/shared/Input/index.jsx
  src/components/shared/Input/input.style.js
  src/pages/Home.jsx
  src/styles/colors.js
  src/styles/global-styles.js
Labels: Passed Code Review

#13 Dockerize the app
  .dockerignore
  .env.sample
  .gitignore
  Dockerfile
  README.md
  bin/boot.sh
  docker-compose.yml
  etc/nginx.conf
Labels: Ready For Code Review

#18 Rev-001: Create homepage's navbar and storyboard
  package-lock.json
  package.json
  setup-jest.js
  src/App.jsx
  src/App.test.jsx
  src/__snapshots__/App.test.jsx.snap
  src/assets/images/avatar.svg
  src/assets/images/chevron-down.svg
  src/assets/images/join-now.svg
  src/assets/images/location-pin-simple.svg
  src/assets/images/notification-bell.svg
  src/assets/images/rounded-search-icon.svg
  src/assets/images/search-icon.svg
  src/assets/images/story-board-image.svg
  src/components/ClaimAddress/index.jsx
  src/components/Header/header.styles.js
  src/components/Header/index.jsx
  src/components/Navbar/UserControlSection.jsx
  src/components/Navbar/index.jsx
  src/components/Navbar/navbar.styles.js
  src/components/Storyboard/index.jsx
  src/components/Storyboard/storyboard.styles.js
  src/components/shared/Footer/SupportInfo.jsx
  src/components/shared/Footer/index.jsx
  src/components/shared/Input/index.jsx
  src/pages/Home.jsx
  src/setupTests.js
  src/styles/colors.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#17 Rev-002: add reverifiplus and explorelistings from homepage
  src/assets/agent.svg
  src/assets/attorney.svg
  src/assets/camera.svg
  src/assets/clean.svg
  src/assets/images/newyork-city.jpg
  src/assets/inspection.svg
  src/assets/insurance.svg
  src/components/ExploreListing/data.js
  src/components/ExploreListing/explore-listing.styles.js
  src/components/ExploreListing/index.jsx
  src/components/ReverifiPlus/index.jsx
  src/components/ReverifiPlus/reverifi-plus.styles.js
  src/styles/colors.js
Labels: Passed Code Review, Ready To Merge

#9 Rev-006-create-signup-page
  package-lock.json
  package.json
  src/assets/icons/apple.svg
  src/assets/icons/chackbox.svg
  src/assets/icons/facebook.svg
  src/assets/icons/google.svg
  src/assets/icons/login-main.svg
  src/assets/icons/sign-up-main.svg
  src/components/ExploreListing/explore-listing.styles.js
  src/components/FeaturedListing/Card/Card.jsx
  src/components/FeaturedListing/Card/card.styles.js
  src/components/FeaturedListing/featured-listing.styles.js
  src/components/Navbar/navbar.styles.js
  src/components/ReverifiPlus/reverifi-plus.styles.js
  src/components/Storyboard/storyboard.styles.js
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/components/shared/FormCheckbox/index.jsx
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormInput/index.jsx
  src/components/shared/Input/input.style.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.test.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.test.jsx
  src/pages/SignUp/sign-up-schema.js
  src/pages/SignUp/sign-up.styles.js
  src/routes.js
  src/setupTests.js
  src/styles/colors.js
  src/styles/global-styles.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Feature Review

#10 Rev-007-create-login-page
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/components/shared/FormInput/form-input.styles.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.test.jsx
  src/pages/Login/login-schema.js
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.test.jsx
  src/pages/SignUp/sign-up.styles.js
  src/setupTests.js
Labels: Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge, Ready For Feature Review

#16 REV-012: create button shared component
  src/components/ClaimAddress/claim-address.styles.js
  src/components/ClaimAddress/index.jsx
  src/components/shared/Button/Button.style.js
  src/components/shared/Button/index.jsx
  src/components/shared/Footer/footer.styles.js
  src/components/shared/Footer/index.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge
