Repository OptimumPartners/reverifi, pull requests merged in 2022-03, with the labels that each got.

#165 REV-153-create-listings-implement-special-tags
  src/assets/icons/tags.svg
  src/components/create-listing/CreateListingForm/create-listing-form-schema.js
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FormInputFields/form-input-fields.styles.js
  src/components/create-listing/FormInputFields/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
Labels: In Code Review, Comments Addressed

#169 REV-176-save-status-is-not-reflected-on-save-icon-on-overlay-or-without-it
  src/components/home/FeaturedListingCard/index.jsx
  src/components/shared/SaveAndShareButtons/index.jsx
Labels: Passed Code Review

#162 REV-146 my listings page bugs
  src/components/my-listings/DeleteBox/delete-box.style.js
  src/components/my-listings/DeleteBox/index.jsx
  src/components/my-listings/ListingsHeader/index.jsx
  src/components/my-listings/ListingsHeader/listings-header.style.js
  src/components/my-listings/ListingsTable/index.jsx
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/my-listings/MyListings/index.jsx
  src/components/my-listings/MyListings/my-listings.js
  src/components/my-listings/MyListings/my-lsitings.style.js
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
  src/components/shared/DropdownMenu/index.jsx
  src/components/shared/Table/table-styles.js
  src/pages/MyListings.jsx
  src/services/listing.js
Labels: In Code Review, Comments Addressed

#168 REV-171-create-saved-listings-tab
  src/assets/images/saved-agent-no-data.svg
  src/assets/images/saved-listing-no-data.svg
  src/components/how-we-work/HowWeWorkWrapper/index.jsx
  src/components/how-we-work/ListingsTable/listings-table.styles.js
  src/components/saved-agents-listings/NoDataComponent/index.jsx
  src/components/saved-agents-listings/NoDataComponent/no-data-component.styles.js
  src/components/saved-agents-listings/SavedAgents/index.jsx
  src/components/saved-agents-listings/SavedAgents/saved-agents.styles.js
  src/components/saved-agents-listings/SavedAgentsListingsWrapper/index.jsx
  src/components/saved-agents-listings/SavedAgentsListingsWrapper/saved-agents-listings-wrapper.styles.js
  src/components/saved-agents-listings/SavedListings/index.jsx
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/components/shared/Table/table-styles.js
  src/components/shared/Tabs/index.jsx
  src/components/shared/Tabs/tabs.styles.js
  src/components/verify-phone/VerifyPhoneForm/index.jsx
  src/pages/Login/Login.jsx
  src/pages/SavedAgentsListings.jsx
  src/routes.js
  src/services/social-statistics.js
Labels: Comments Addressed

#167 REV-166-create-reverifi-coming-soon-page
  src/assets/images/reverifi-coming-soon.png
  src/components/dashboard/DashboardWrapper/index.jsx
  src/components/edit-listing-schedule/DateInput/index.jsx
  src/components/edit-listing-schedule/TimeInput/index.jsx
  src/components/edit-listing/ReverifiPlus/reverifi-plus.style.js
  src/components/edit-listing/Tabs/index.jsx
  src/components/shared/Tabs/index.jsx
  src/components/shared/Tabs/tabs.styles.js
Labels: In Code Review, Comments Addressed

#170 REV-161-remove-fields-borders
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/home/FeaturedListing/index.jsx
  src/components/shared/Tooltip/index.jsx
  src/components/shared/Tooltip/tooltip.styles.js
Labels: Comments Addressed, Passed Code Review

#172 REV-153- fix
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FormInputFields/index.jsx
Labels: Ready For Code Review

#175 fix-saved-agents-listings
  src/components/saved-agents-listings/SavedAgentsListingsWrapper/index.jsx
Labels: Ready For Code Review

#173 REV-181-details-schedule-reverifi-tabs-are-not-shown-in-edit-listing-page
  src/components/edit-listing/Tabs/index.jsx
Labels: Ready For Code Review

#176 REV-183 implement search page google map
  public/index.html
  src/assets/images/search-no-data.png
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/MapCard/index.jsx
  src/components/listing-search-page/MapCard/map-card.style.js
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchList/search-list.style.js
  src/components/shared/Map/index.jsx
  src/components/shared/Marker/index.jsx
Labels: Passed Code Review

#177 REV-187-page-title-should-be-saved-not-saved-listings-in-header-menu
  src/components/shared/Navbar/index.jsx
Labels: Ready For Code Review

#174 REV-180-tags-selection-enhancement
  src/components/agent-details/AgentListings/index.jsx
  src/components/agent-details/CardImage/card-image.style.js
  src/components/agent-details/CardImage/index.jsx
  src/components/create-listing/FormInputFields/form-input-fields.styles.js
  src/components/create-listing/FormInputFields/index.jsx
Labels: Comments Addressed, Passed Code Review

#183 REV-193-saved-page-top-edges-of-tables-should-be-rounded
  src/components/shared/Table/table-styles.js
Labels: Ready For Code Review

#182 REV-199 saved page arrows at the bottom behaviour
  src/components/edit-listing-schedule/ListingSchedule/index.jsx
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/saved-agents-listings/SavedAgents/index.jsx
  src/components/saved-agents-listings/SavedListings/index.jsx
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
Labels: Ready For Code Review

#179 REV-186-when-pressing-on-save-or-share-buttons-in-search-listings-page-the-user-is-redirected-to-the-listings-page
  src/assets/arrow-right-green.svg
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
Labels: Passed Code Review

#180 REV-188-saved-agents-profile-picture-of-agent-when-no-image-is-uploaded-should-be-squared
  src/assets/icons/saved-agent-placeholder.svg
  src/components/saved-agents-listings/SavedAgents/index.jsx
  src/components/saved-agents-listings/SavedAgents/saved-agents.styles.js
Labels: Passed Code Review

#181 REV-189-saved-listing-saved-agent-pages
  src/components/saved-agents-listings/SavedAgents/index.jsx
Labels: Passed Code Review

#184 REV-195-my-roles-column-saved-agents-tab
  src/components/saved-agents-listings/SavedAgents/index.jsx
  src/components/shared/Table/table-styles.js
Labels: Passed Code Review

#185 REV-196-the-saved-agents-page-design-is-ruined-when-agents-have-long-name-phone-roles-email-address-infromation
  src/components/saved-agents-listings/SavedAgents/index.jsx
Labels: Ready For Code Review

#188 REV-190-search-listings-page-labels-are-wrapped-and-truncated
  src/components/listing-search-page/Card/card.style.js
Labels: Ready For Code Review

#189 REV-198-saved-saved-listings-saved-agents-disappear-when-editing-my-profile-informtion
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/saved-agents-listings/SavedListings/index.jsx
Labels: Ready For Code Review

#190 REV-200-saved-the-user-is-still-in-saved-agents-page-even-when-they-are-not-agents-anymore
  src/components/saved-agents-listings/SavedAgents/index.jsx
Labels: Ready For Code Review

#191 REV-201-saved-signing-up-using-long-email-will-ruin-saved-agents-page-design
  src/pages/SignUp/SignUp.jsx
Labels: Ready For Code Review

#186 REV-204 my roles update the table
  src/components/how-we-work/ListingsTable/index.jsx
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/my-roles/RolesTable/index.jsx
  src/components/my-roles/RolesTable/roles-table.style.js
  src/components/shared/Tooltip/index.jsx
  src/components/shared/Tooltip/tooltip.styles.js
Labels: UnAddressed Comments, Passed Code Review

#187 REV-185-add-address-field-into-create-listing-and-edit-listing
  public/index.html
  src/components/create-listing/CreateListingForm/create-listing-form-schema.js
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FormInputFields/form-input-fields.styles.js
  src/components/create-listing/FormInputFields/index.jsx
  src/components/create-listing/ListingFormMap/index.jsx
  src/components/create-listing/ListingFormMap/listing-form-map.styles.js
  src/components/home/Storyboard/index.jsx
  src/components/home/Storyboard/storyboard.styles.js
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/LocationSearchInput/index.jsx
  src/components/shared/LocationSearchInput/search-input.style.js
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review

#200 REV-258-search-clicking-on-x-button-should-not-reset-the-query
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/SearchHeader/index.jsx
Labels: Passed Code Review

#192 REV-202-rate-review-date
  src/components/agent-details/AgentRating/index.jsx
Labels: Ready For Code Review

#193 REV-203-rate-review-when-editing-one-of-the-reviews-and-saving-it-the-char-number-doesnt-change
  src/components/agent-details/AgentRating/index.jsx
  src/components/shared/FormTextArea/index.jsx
Labels: Ready For Code Review

#194 REV-156 edit listings page issues
  src/components/create-listing/CreateListingForm/index.jsx
Labels: Ready For Code Review

#195 REV-232-schedule the first scheduled visiting time isnt reflected on listing details page
  src/components/listing-page/ScheduleVisit/index.jsx
Labels: Ready For Code Review

#196 REV-236 schedule listing detailed page
  src/components/listing-page/ScheduleVisit/data.js
Labels: Ready For Code Review

#198 REV-210-rate-review-like-button-issue
  src/assets/icons/agent-detailes-like.svg
  src/assets/icons8-share.svg
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/shared/LikeButton/index.jsx
  src/components/shared/LikeButton/like-button.styles.js
Labels: Ready For Code Review

#199 REV-252-search-listing-data-are-not-rendering-correctly
  src/components/home/Storyboard/index.jsx
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/MapCard/index.jsx
Labels: Comments Addressed, Passed Code Review

#202 REV-211-rate-review-broken-ratings-reviews-and-date-time-at-certain-viewports
  src/components/agent-details/AgentRating/agent-rating.style.js
Labels: Ready For Code Review

#201 REV-260 fix schedule bugs
  src/components/edit-listing-schedule/DateInput/date-input.style.js
  src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.style.js
  src/components/edit-listing-schedule/ListingSchedule/index.jsx
  src/components/edit-listing-schedule/ListingSchedule/listing-schedule-schema.js
  src/components/edit-listing-schedule/TimeInput/index.jsx
  src/components/edit-listing-schedule/TimeInput/time-input.style.js
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/utils/helpers.js
Labels: In Code Review, Comments Addressed

#203 Hot fix homepage search input
  src/components/home/Storyboard/index.jsx
  src/components/shared/Map/index.jsx
Labels: Ready For Code Review

#205 REV-261-search-listings-page-number-of-listings-in-subtitle-doesnt-match-with-the-number-of-listings-card-shown
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchResults/listing-search-cards.style.js
Labels: Ready For Code Review

#204 REV-266-search-listings-update-search-cards
  src/components/listing-search-page/MapCard/index.jsx
  src/components/listing-search-page/MapCard/map-card.style.js
Labels: Comments Addressed, Passed Code Review

#206 REV-247-saved-fix-tables-alignments
  src/components/shared/Table/table-styles.js
Labels: Ready For Code Review

#208 REV-268-search-listing-auto-complete-is-not-provided-for-listings-search-box
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchHeader/search-header.style.js
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
Labels: Passed Code Review

#209 REV-225 create new listing update year built validation message
  src/components/create-listing/CreateListingForm/create-listing-form-schema.js
  src/components/create-listing/FormInputFields/index.jsx
  src/components/create-listing/ListingImageInput/index.jsx
  src/components/create-listing/ListingImageInput/listingImageInput.styles.js
  src/components/edit-listing-schedule/TimeInput/index.jsx
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormSelectInput/index.jsx
  src/components/shared/FormSelectInput/select.styles.js
  src/utils/helpers.js
Labels: Ready For Code Review

#214 create shared pagination component
  src/components/how-we-work/ListingsTable/index.jsx
  src/components/my-listings/ListingsHeader/listings-header.style.js
  src/components/my-listings/ListingsTable/index.jsx
  src/components/my-listings/MyListings/index.jsx
  src/components/my-listings/MyListings/my-listings.js
  src/components/my-roles/RolesTable/index.jsx
  src/components/saved-agents-listings/SavedAgents/index.jsx
  src/components/saved-agents-listings/SavedListings/index.jsx
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
  src/components/shared/Pagination/index.jsx
  src/components/shared/Pagination/pagination.styles.js
  src/utils/constants.js
Labels: In Code Review, Comments Addressed

#211 REV-218-agent-profile-hide-social-media-icons-when-no-social-accounts-inserted
  src/components/agent-details/AgentInformation/index.jsx
Labels: Ready For Code Review

#210 REV-217-rate-and-review-rating-with-s
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AgentRating/index.jsx
  src/components/agent-details/CardImage/card-image.style.js
Labels: Ready For Code Review

#212 REV-244-saved-listing-overlapping-happens-when-the-seller-name-is-too-long
  src/components/saved-agents-listings/SavedListings/index.jsx
Labels: Ready For Code Review

#213 REV-222-special-tags-deleting-any-of-tags-wont-produce-the-tags-menu-again
  src/components/create-listing/FormInputFields/index.jsx
Labels: Ready For Code Review

#219 Hot-fix: Release update, Remove node_modules duplicate cmds
  .eslintrc
  .github/workflows/cicd.yml
  .gitignore
Labels: Ready For Code Review

#220 REV-224-lhs-menu-logout-is-not-working
  src/components/shared/Navbar/index.jsx
  src/components/shared/Sidebar/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
Labels: Ready For Code Review

#215 REV-280-schedule request time toast message
  src/components/edit-listing-schedule/ListingSchedule/index.jsx
  src/components/edit-listing-schedule/TimeInput/index.jsx
  src/components/edit-listing-schedule/TimeInput/time-input.style.js
  src/components/listing-page/ScheduleVisit/data.js
  src/components/listing-page/ScheduleVisit/index.jsx
Labels: Comments Addressed, Passed Code Review

#139 Transaction first step
  src/assets/icons/achieved-step-icon.svg
  src/assets/icons/gray-buyer-agent.svg
  src/assets/icons/gray-buyer-group.svg
  src/assets/icons/gray-seller-address.svg
  src/assets/icons/gray-seller-name.svg
  src/assets/icons/gray-seller.svg
  src/assets/images/wide-apartment2.png
  src/components/how-we-work/ListingsTable/index.jsx
  src/components/shared/FormSelectInput/select.styles.js
  src/components/shared/StepProgressBar/index.jsx
  src/components/shared/StepProgressBar/step-progress-bar.styles.js
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper-schema.js
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AgentCard/agent-card.styles.js
  src/components/transaction/AgentCard/index.jsx
  src/components/transaction/DataCard/data-card.styles.js
  src/components/transaction/DataCard/index.jsx
  src/components/transaction/TransactionListingDataWrapper/index.jsx
  src/components/transaction/TransactionListingDataWrapper/transaction-listing-data-wrapper.styles.js
  src/components/transaction/TransactionSharedComponent/index.jsx
  src/components/transaction/TransactionSharedComponent/transaction-shared-component.styles.js
  src/pages/Transaction/routes.js
  src/routes.js
  src/services/user.js
  src/styles/colors.js
Labels: Passed Code Review

#221 REV-246-edit-listing-i-am-seller-and-seller-agent-buttons-features-updates
  src/components/create-listing/CreateListingForm/index.jsx
Labels: Passed Code Review

#227 REV-371-remove-listings-table-from-how-we-work
  src/components/dashboard/DashboardWrapper/dashboard-wrapper.styles.js
  src/components/dashboard/DashboardWrapper/index.jsx
  src/components/dashboard/data.js
  src/components/how-we-work/HowWeWorkWrapper/index.jsx
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/shared/StepProgressBar/step-progress-bar.styles.js
  src/components/shared/Table/table-styles.js
  src/components/transaction-info/ListingsTable/index.jsx
  src/components/transaction-info/ListingsTable/listings-table.styles.js
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionInfoWrapper/transaction-info-wrapper.styles.js
  src/components/transaction-info/TransactionsTable/index.jsx
  src/components/transaction-info/TransactionsTable/transactions-table.styles.js
  src/pages/TransactionInfo.jsx
  src/routes.js
Labels: Ready For Code Review

#228 REV-133-transaction-flow-step-03-front-end
  src/assets/icons/transaction-step3-delete.svg
  src/assets/icons/transaction-step3-download.svg
  src/assets/icons/transaction-step3-eye.svg
  src/assets/icons/transaction-step3-print.svg
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
  src/components/shared/Table/table-styles.js
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/components/transaction/UploadDocumentsWrapper/upload-documents-wrapper.styles.js
  src/pages/Transaction/UploadDocuments.jsx
  src/pages/Transaction/routes.js
Labels: Ready For Code Review

#224 REV-314 update search price filters
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/SearchHeader/filter-data.js
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchHeader/search-header.style.js
  src/components/shared/CustomMenuList/index.jsx
  src/components/shared/CustomValueContainer/index.jsx
  src/services/listing.js
Labels: Comments Addressed

#231 REV-135 transaction flow-step 04
  src/components/listing-search-page/SearchHeader/filter-data.js
  src/components/shared/Table/table-styles.js
  src/components/transaction-info/ListingsTable/index.jsx
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
  src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js
  src/components/transaction/CloseDealWrapper/index.jsx
  src/pages/Transaction/CloseDeal.jsx
  src/pages/Transaction/routes.js
  src/services/listing.js
  src/services/transactions.js
  src/utils/constants.js
Labels: Ready For Code Review

#232 Update CICD to use nvm
  .github/workflows/cicd.yml
Labels: In Code Review

#225 REV-299-search listing page
  src/components/edit-listing-schedule/DateInput/date-input.style.js
  src/components/edit-listing-schedule/DateInput/index.jsx
  src/components/edit-listing-schedule/TimeInput/time-input.style.js
  src/components/home/Storyboard/index.jsx
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchList/search-list.style.js
  src/components/shared/CustomMenuList/index.jsx
  src/utils/constants.js
Labels: In Code Review, Comments Addressed

#230 REV-346-connect-step-01-step-02
  src/components/shared/DropdownMenu/index.jsx
  src/components/shared/FormInput/index.jsx
  src/components/shared/TransactionSelectInput/index.jsx
  src/components/shared/TransactionSelectInput/transaction-select-input.styles.js
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper-schema.js
  src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper.styles.js
  src/components/transaction/AssignTasksWrapper/index.jsx
  src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js
  src/components/transaction/CloseDealWrapper/index.jsx
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/pages/Transaction/AssignTasks.jsx
  src/services/transactions.js
Labels: In Code Review, UnAddressed Comments, Needs Rebase

#234 REV-390-uploading-assets- Single image upload
  Dockerfile
  src/components/create-listing/ListingImageInput/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/UploadInput/index.jsx
  src/components/shared/UploadInput/uploadInput.styles.js
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/services/upload.js
Labels: In Development

#226 Implement points module
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/achievements.svg
  src/assets/images/achievements.png
  src/assets/notification.svg
  src/components/achievements/AchievementsContent/achievements-content.styles.js
  src/components/achievements/AchievementsContent/index.jsx
  src/components/achievements/UserActivity/index.jsx
  src/components/achievements/UserActivity/user-activity.styles.js
  src/components/achievements/achievementsSidebar/achievements-sidebar.styles.js
  src/components/achievements/achievementsSidebar/index.jsx
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/notifications/notification.jsx
  src/components/notifications/notifications.jsx
  src/components/notifications/styles.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/components/shared/Sidebar/index.jsx
  src/contexts/PointsNotificationContext/PointsNotificationContext.jsx
  src/contexts/UserContext/index.jsx
  src/pages/Achievements.jsx
  src/pages/SignUp/SignUp.jsx
  src/routes.js
  src/services/points-service.js
  src/styles/colors.js
  src/utils/constants.js
  src/utils/formatDate.js
Labels: Needs Rebase, Ready For Code Review

#240 REV-418-transaction-for-the-recipient-when-the-deal-is-closed
  src/components/transaction/CloseDealWrapper/index.jsx
Labels: Ready For Code Review

#239 REV-414-signup-is-not-working
  src/components/home/Events/events.styles.js
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/pages/SignUp/SignUp.jsx
Labels: Comments Addressed, Passed Code Review

#235 update completed pages the confirmed images
  src/assets/icons/share-listing-main.svg
  src/assets/images/my-listings-image.png
  src/assets/images/reverifi-coming-soon.png
  src/assets/images/saved-agent-no-data.svg
  src/assets/result-not-found-agents.svg
  src/components/agent-list/ResultNotFound/index.jsx
  src/components/agent-list/ResultNotFound/result.styles.js
Labels: In Code Review, Comments Addressed

#237 REV-398-transaction-flow-step-3
  .eslintrc
  src/assets/images/loading.gif
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/Table/table-styles.js
  src/components/shared/UploadInput/index.jsx
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/components/transaction/UploadDocumentsWrapper/upload-documents-wrapper.styles.js
  src/services/transactions.js
  src/services/upload.js
Labels: Comments Addressed, Passed Code Review

#114 REv-16+REV-17: Social Login and Signup
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/contexts/UserContext/index.jsx
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/services/auth.js
Labels: Ready For Code Review, Unmerged dependency in other repo

#250 REV-422-dashboard accepted and declined buttons
  src/components/dashboard/InvitationsTable/index.jsx
  src/components/shared/Table/table-styles.js
  src/components/transaction-info/ListingsTable/index.jsx
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/pages/SignUp/sign-up-schema.js
Labels: Passed Code Review

#246 REV-412-transaction-the-user-should-be-able-to-go-to-the-four-transaction-flow-steps-from-my-transactions-table
  src/components/transaction-info/ListingsTable/index.jsx
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
  src/components/transaction-info/TransactionsTable/transactions-table.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AssignTasksWrapper/index.jsx
  src/components/transaction/CloseDealWrapper/index.jsx
  src/components/transaction/TransactionSharedComponent/index.jsx
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/pages/Transaction/routes.js
  src/utils/constants.js
Labels: Comments Addressed, Passed Code Review

#242 REV-167-offers-table purchase counter offer forms
  src/assets/images/submit-offer.png
  src/components/dashboard/OffersTable/index.jsx
  src/components/dashboard/OffersTable/offers-table.styles.js
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/SubmitOffer/index.jsx
  src/components/listing-page/SubmitOffer/submit-offer-schema.js
  src/components/listing-page/SubmitOffer/submit-offer.style.js
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/shared/FilesList/index.jsx
  src/components/shared/ListingImageInput/index.jsx
  src/components/shared/ListingImageInput/listingImageInput.styles.js
  src/components/transaction-info/ListingsTable/index.jsx
  src/contexts/ShowModalContext/index.jsx
  src/pages/Listing/ListingPage.jsx
  src/services/purchase-offer.js
  src/services/user.js
Labels: Comments Addressed, Passed Code Review

#249 REV-441-loading issue while navigating between pages
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
Labels: Comments Addressed, Passed Code Review

#251 REV-440-step-01-updates
  src/components/shared/DatePickerInput/index.jsx
  src/components/shared/TransactionSelectInput/index.jsx
  src/components/shared/TransactionSelectInput/transaction-select-input.styles.js
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper-schema.js
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AssignTasksWrapper/assign-processes-schema.js
  src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper-schema.js
  src/components/transaction/AssignTasksWrapper/assignees-schema.js
  src/components/transaction/AssignTasksWrapper/index.jsx
  src/components/transaction/InviteModal/index.jsx
Labels: In Code Review, UnAddressed Comments

#257 REV-457-transaction-uploads-are-the-same-once-uploaded-for-all-transactions
  src/components/transaction/TransactionListingDataWrapper/index.jsx
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/components/transaction/UploadDocumentsWrapper/upload-documents-wrapper.styles.js
  src/services/transactions.js
Labels: Passed Code Review

#256 REV-413-dashboard-invitation-when-the-user-sends-transaction-invitation-it-should-only-be-reflected-on-sent-tab
  src/components/dashboard/InvitationsTable/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
Labels: Passed Code Review

#259 add points on registration
  src/components/achievements/achievementsSidebar/achievements-sidebar.styles.js
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review

#258 REV-397 change some images
  src/assets/images/saved-agent-no-data.svg
  src/assets/images/saved-listing-no-data.svg
Labels: Passed Code Review

#261 REV-463-update-docs-title-for-nj-only
  src/components/dashboard/InvitationsTable/index.jsx
  src/components/dashboard/InvitationsTable/invitations-table.styles.js
Labels: Ready For Code Review

#260 REV-439-input-in-invitation-pop-up-to-be-reflected-on-origin-field
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AssignTasksWrapper/index.jsx
  src/components/transaction/InviteModal/index.jsx
  src/utils/constants.js
Labels: Ready For Code Review

#262 REV-465 add fixed hero image
  src/assets/images/transaction-apartment.png
  src/components/transaction/TransactionListingDataWrapper/index.jsx
Labels: Ready For Code Review

#263 REV-435-fix invitation table
  src/components/dashboard/InvitationsTable/index.jsx
Labels: Ready For Code Review

#264 REV-466-my-transactions-for-the-buyer-team-the-transaction-isnt-displayed-on-their-my-transactions-table
  src/components/transaction-info/TransactionsTable/index.jsx
Labels: Passed Code Review

#265 REV-436 transaction add involved parties email
  docker-compose.yml
  src/components/transaction/AgentCard/agent-card.styles.js
  src/components/transaction/AgentCard/index.jsx
  src/components/transaction/DataCard/data-card.styles.js
  src/components/transaction/DataCard/index.jsx
Labels: Passed Code Review

#270 REV-460-step-03-download-is-not-working-print-to-be-removed
  src/components/transaction/UploadDocumentsWrapper/index.jsx
Labels: Passed Code Review

#280 REV-461 fix my listings table as expected design
  src/components/my-listings/ListingsTable/listing-table.style.js
Labels: Passed Code Review

#274 fix design
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
Labels: Passed Code Review

#276 REV-311 fix overlapping for autocomplete listing
  src/components/shared/LocationSearchInput/search-input.style.js
Labels: Passed Code Review

#275 REV-292 fix tool-tip issue
  src/components/my-roles/RolesTable/index.jsx
Labels: Passed Code Review

#273 REV-244 fix saved listing issue
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
Labels: Passed Code Review

#277 REV-444-step-02-dates-should-be-single-date
  src/components/shared/DatePickerInput/date-picker-input.styles.js
  src/components/shared/DatePickerInput/index.jsx
  src/components/transaction/AssignTasksWrapper/assign-processes-schema.js
  src/components/transaction/AssignTasksWrapper/index.jsx
Labels: Passed Code Review

#269 REV-468-profile-page-profile-image-is-not-working
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/contexts/UserContext/index.jsx
Labels: Comments Addressed, Passed Code Review

#272 REV-141 fix some issues
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/my-roles/RoleCard/role-card.styles.js
  src/components/my-roles/Roles/index.jsx
  src/components/my-roles/Roles/roles.styles.js
Labels: Comments Addressed, Passed Code Review

#281 REV-221 fix button on edit listings as on figma
  src/components/shared/Button/Button.style.js
Labels: Passed Code Review

#284 REV-362 fix services and languages area select
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
Labels: Passed Code Review

#290 REV-444-fix
  src/components/shared/DatePickerInput/date-picker-input.styles.js
  src/components/shared/TransactionSelectInput/transaction-select-input.styles.js
  src/components/transaction/AssignTasksWrapper/index.jsx
Labels: Comments Addressed, Passed Code Review

#288 REV-399-step-01 add new field for final selling price
  src/components/home/Storyboard/index.jsx
  src/components/shared/Toast/index.jsx
  src/components/shared/Toast/toast.styles.js
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction/CloseDealWrapper/close-deal-wrapper.styles.js
  src/components/transaction/CloseDealWrapper/index.jsx
Labels: Comments Addressed

#291 REV-377-access-to-transaction-to-be-granted-to-certain-roles
  src/components/transaction-info/ListingsTable/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
Labels: Passed Code Review

#278 REV-402 transaction page add a message when no data found
  src/components/dashboard/DashboardWrapper/index.jsx
  src/components/dashboard/InvitationsTable/index.jsx
  src/components/dashboard/OffersTable/index.jsx
  src/components/listing-page/SubmitOffer/index.jsx
  src/components/my-roles/RolesTable/index.jsx
  src/components/shared/TableNoData/index.jsx
  src/components/shared/TableNoData/table-no-data.style.js
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction/AgentCard/agent-card.styles.js
  src/components/transaction/AgentCard/index.jsx
  src/components/transaction/DataCard/data-card.styles.js
  src/components/transaction/DataCard/index.jsx
Labels: Comments Addressed, Passed Code Review

#286 REV-456-create-listing-edit-listing-upload-images
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/ListingImageInput/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/FilesList/filesList.styles.js
  src/components/shared/FilesList/index.jsx
  src/components/transaction/UploadDocumentsWrapper/index.jsx
  src/services/listing.js
  src/services/upload.js
Labels: Passed Code Review

#295 REV-491-create-transaction-summary-report
  src/assets/icons/transaction-summary-complete.svg
  src/assets/icons/transaction-summary-overdue.svg
  src/assets/icons/transaction-summary-todo.svg
  src/components/shared/Modal/modal.styles.js
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionSummaryModal/index.jsx
  src/components/transaction-info/TransactionSummaryModal/transaction-summary-modal.styles.js
  src/components/transaction-info/TransactionsTable/index.jsx
Labels: Comments Addressed, Passed Code Review

#296 REV-399-add final price
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper-schema.js
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
Labels: Ready For Code Review

#308 REV-517 Add fix notes field width
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
Labels: Passed Code Review

#282 remove comma
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/my-roles/RolesTable/index.jsx
Labels: Comments Addressed, Passed Code Review

#285 fix verify you phone page
  src/components/verify-phone/VerifyPhoneForm/index.jsx
  src/components/verify-phone/VerifyPhoneForm/verify-phone-form.styles.js
Labels: Comments Addressed, Passed Code Review

#297 REV-510-replace lot sqft with garages
  src/components/agent-details/AgentListings/index.jsx
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-search-page/Card/index.jsx
Labels: Passed Code Review

#299 REV-370 fix form expanded when submit empty form
  src/components/listing-page/ContactForm/contact-form.styles.js
Labels: Passed Code Review

#302 REV-383 fix leading zeros
  src/components/listing-page/Details/index.jsx
Labels: Passed Code Review

#303 REV-456-fix-2
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/ListingImageInput/index.jsx
  src/components/create-listing/ListingImageInput/listingImageInput.styles.js
  src/components/shared/FilesList/filesList.styles.js
Labels: Passed Code Review

#304 REV-320 user can save listings from agent
  src/components/agent-details/CardInformation/index.jsx
Labels: Passed Code Review

#305 REV-11-claim-address-functionality
  src/assets/images/claim-property.png
  src/assets/images/loading.gif
  src/components/create-listing/ListingImageInput/index.jsx
  src/components/listing-page/ClaimPropertyModal/claim-property-modal.styles.js
  src/components/listing-page/ClaimPropertyModal/index.jsx
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/shared/FilesList/index.jsx
  src/components/shared/Modal/modal.styles.js
  src/pages/Listing/ListingPage.jsx
  src/services/listing.js
Labels: Passed Code Review

#307 REV-511-fix
  src/components/transaction-info/TransactionInfoWrapper/index.jsx
  src/components/transaction-info/TransactionsTable/index.jsx
Labels: Passed Code Review

#318 REV-11-FIX
  src/components/listing-page/ClaimPropertyModal/index.jsx
  src/services/listing.js
Labels: Passed Code Review

#317 Rev 510 listings cards remove sqft
  src/components/agent-details/CardInformation/index.jsx
  src/components/listing-search-page/MapCard/index.jsx
Labels: Passed Code Review

#316 REV-55 create 404 page
  src/assets/images/not-found.png
  src/components/notFound/index.jsx
  src/components/notFound/not-found.style.js
  src/pages/NotFound.jsx
Labels: Comments Addressed, Passed Code Review

#312 REV-522 remove filters from my listings page
  src/components/my-listings/ListingsHeader/index.jsx
Labels: Passed Code Review

#301 REV-354-374 fixed fire fox issues
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/saved-agents-listings/SavedListings/saved-listings.styles.js
Labels: Comments Addressed, Passed Code Review

#300 REV-353 fix border on firefox browser
  src/components/agent-list/AgentCard/agent-card.styles.js
Labels: Comments Addressed, Passed Code Review

#293 change font weight
  src/components/listing-search-page/SearchList/search-list.style.js
Labels: Comments Addressed, Passed Code Review

#314 add confirm password field to signup page
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up-schema.js
Labels: In Code Review, Passed Code Review
