Repository OptimumPartners/reverifi, pull requests merged in 2022-02, with the labels that each got.

#58 REV-51: update fav icons logo and hovers
  public/favicon.ico
  public/index.html
  src/assets/icons/account-settings.svg
  src/assets/icons/dashboard-menu.svg
  src/assets/icons/saved-listing.svg
  src/assets/icons/saved-searches.svg
  src/assets/icons/sign-out.svg
  src/components/create-listing/FeatureSelection/feature-selection.styles.js
  src/components/create-listing/FormInputFields/form-input-fields.styles.js
  src/components/home/Card/card.styles.js
  src/components/home/ClaimAddress/claim-address.styles.js
  src/components/home/ExploreListing/explore-listing.styles.js
  src/components/home/ExploreListing/index.jsx
  src/components/home/FeaturedListing/featured-listing.styles.js
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/shared/Button/Button.style.js
  src/components/shared/Footer/footer.styles.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/pages/SignUp/sign-up.styles.js
Labels: Passed Feature Review, Passed Code Review, Ready To Merge

#63 Hot-fix: Css Stylings are failing due to prettier error
  src/components/home/ExploreListing/explore-listing.styles.js
Labels: Passed Code Review, Ready To Merge

#62 REV-56 UI tweaks - Signup & login
  src/assets/icons/facebook.svg
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up-schema.js
  src/pages/SignUp/sign-up.styles.js
Labels: Passed Feature Review, Ready for QA, Passed Code Review

#61 REV-48 my profile page
  package-lock.json
  package.json
  src/assets/icons/profile-about.svg
  src/assets/icons/profile-address.svg
  src/assets/icons/profile-company-name.svg
  src/assets/icons/profile-company-website.svg
  src/assets/icons/profile-email.svg
  src/assets/icons/profile-facebook.svg
  src/assets/icons/profile-insta.svg
  src/assets/icons/profile-languages.svg
  src/assets/icons/profile-linkedin.svg
  src/assets/icons/profile-name.svg
  src/assets/icons/profile-phone.svg
  src/assets/icons/profile-service-areas.svg
  src/assets/icons/profile-youtube.svg
  src/assets/icons/user-image-edit.svg
  src/components/home/FeaturedListing/data.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
  src/components/shared/DropdownMenu/index.jsx
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormInput/index.jsx
  src/components/shared/FormTextArea/form-text-area.styles.js
  src/components/shared/FormTextArea/index.jsx
  src/contexts/UserContext/index.jsx
  src/pages/MyProfile.jsx
  src/routes.js
  src/services/user.js
  src/utils/helpers.js
Labels: Passed Feature Review, Ready for QA, Comments Addressed, Passed Code Review

#55 REV-25-fetch agents and pagination and type search
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/agent-list/AgentsListBanner/agents-list-banner.styles.js
  src/components/agent-list/AgentsListBanner/index.jsx
  src/components/agent-list/DesktopFilterSection/desktop-filter-section.styles.js
  src/components/agent-list/DesktopFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/mobile-filter-section.styles.js
  src/hooks/use-on-screen.js
  src/pages/AgentList.jsx
  src/services/user.js
  src/utils/helpers.js
Labels: Passed Feature Review, Ready for QA, Comments Addressed, Passed Code Review

#65 REV-58 ui-tweaks-phone-verification
  src/components/verify-phone/VerifyPhoneForm/index.jsx
  src/components/verify-phone/VerifyPhoneForm/verify-phone-form.styles.js
  src/components/verify-phone/VerifyPhoneWrapper/verify-phone-wrapper.styles.js
Labels: Passed Feature Review, Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge

#64 Rev 52 UI tweaks
  src/assets/add-icon.svg
  src/assets/icons/air-conditioner.svg
  src/assets/icons/bathtub.svg
  src/assets/icons/bedroom.svg
  src/assets/icons/bench.svg
  src/assets/icons/wifi.svg
  src/assets/logo.svg
  src/assets/map-claim-address.svg
  src/assets/map-small.svg
  src/assets/share-icon.svg
  src/components/home/Card/card.styles.js
  src/components/home/ClaimAddress/claim-address.styles.js
  src/components/home/ClaimAddress/index.jsx
  src/components/home/Events/index.jsx
  src/components/home/ExploreListing/explore-listing.styles.js
  src/components/home/ExploreListing/index.jsx
  src/components/home/FeaturedListing/featured-listing.styles.js
  src/components/home/FeaturedListing/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/home/ReverifiPlus/reverifi-plus.styles.js
  src/components/home/Storyboard/storyboard.styles.js
  src/components/shared/Footer/SupportInfo.jsx
  src/components/shared/Footer/footer.styles.js
  src/components/shared/Footer/index.jsx
  src/components/shared/Input/input.style.js
  src/components/shared/Navbar/navbar.styles.js
  src/services/user.js
Labels: Passed Feature Review, Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge

#60 REV-54-connect listing page with backend
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/listing-page/Details/index.jsx
  src/components/listing-page/Features/data.js
  src/components/listing-page/Features/features.styles.js
  src/components/listing-page/Features/index.jsx
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/listing-page/Slider/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/pages/Listing/ListingPage.jsx
  src/routes.js
  src/services/listing.js
Labels: Passed Feature Review, Ready for QA, Comments Addressed, Passed Code Review

#67 REV-64-login-page-login-button-font-size
  src/pages/Login/Login.jsx
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Feature Review

#68 REV-66-homepage-join-us-banner-is-broken
  src/components/home/ClaimAddress/claim-address.styles.js
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#70 Rev 65 homepage upcoming tab slides are broken
  src/components/home/Events/data.js
  src/components/home/Events/index.jsx
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Feature Review

#72 REV-70-homepage featured listing cards are broken
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#76 REV-73 homepage search box placeholder needs to be changed
  src/components/home/Storyboard/index.jsx
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#77 Rev-76 update the header menu
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#80 REV-78 homepage footer ui tweaks
  src/components/shared/Footer/footer.styles.js
  src/components/shared/Footer/index.jsx
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#79 REV-77-find-an-agent-should-redirect-to-agent-list
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Feature Review

#75 REV-69-signup-page-no-validation-message-appears-when-entering-pre-registered-account
  src/pages/SignUp/SignUp.jsx
Labels: Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#74 REV-74-login-page-and-signup-pages-auto-saved-fields-restricts-login-and-signup-procces
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#78 REV-75-mobile-verification-add-a-text-above-the-code
  src/components/verify-phone/VerifyPhoneWrapper/index.jsx
  src/contexts/UserContext/index.jsx
  src/pages/SignUp/SignUp.jsx
  src/services/auth.js
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Feature Review

#81 REV-78-homepage-footer-ui-tweaks-update
  src/components/shared/Footer/index.jsx
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#82 HOTFIX: remove conflict error in login page
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review, Ready To Merge

#66 REV-63-signup-page-phone-number-fields-format-are-wrong
  src/components/shared/FormInput/index.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge, Ready For Feature Review

#69 REV-67-homepage-enhancements
  src/components/home/Card/card.styles.js
  src/components/home/ClaimAddress/claim-address.styles.js
  src/components/home/ExploreListing/explore-listing.styles.js
Labels: Ready for QA, Passed Code Review, Ready To Merge, Ready For Feature Review

#73 REV-71-signup-page-no-restrictions-on-password-field
  src/pages/SignUp/sign-up-schema.js
Labels: Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge, Ready For Code Review, Ready For Feature Review

#71 REV-68-login-page-email-and-password-fields-validation-messages-are-not-appeared
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
Labels: Ready for QA, Comments Addressed, Passed Code Review, Ready To Merge, Ready For Feature Review

#83 REV-82 homepage featured listing card enhancements
  src/assets/icons/wifi.svg
  src/components/home/Card/card.styles.js
  src/components/home/FeaturedListing/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/shared/Navbar/navbar.styles.js
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#84 REV-79-account-settings-should-redirect-to-my-profile-page
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/Navbar/index.jsx
  src/pages/SignUp/SignUp.jsx
Labels: In Code Review, Passed Code Review, Ready To Merge, Ready For Code Review

#85 REV-80 agents list page enhacments
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge, Ready For Code Review

#87 REV-81-header-search-for-property-placeholder-sapces-between-profile-image-and-name
  src/components/shared/Navbar/navbar.styles.js
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#90 REV-88-my-profile-x-button-hover-state-selected-items-design
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
Labels: Passed Code Review, Ready To Merge, Ready For Code Review

#92 REV-95-my-profile-save-personal-information-validation-messages
  src/components/shared/Navbar/index.jsx
Labels: Passed Code Review, Ready To Merge

#91 REV-91-clicking-on-continue-should-redirect-to-phone-verification-page
  src/components/verify-phone/VerifyPhoneWrapper/index.jsx
  src/pages/SignUp/SignUp.jsx
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#88 REV-86-my-profile-icons-in-social-media-information-are-not-colored
  src/assets/icons/profile-facebook.svg
  src/assets/icons/profile-insta.svg
  src/assets/icons/profile-linkedin.svg
  src/assets/icons/profile-youtube.svg
Labels: Passed Code Review, Ready To Merge

#86 REV-83-my-profile-fields-capitalization-issues
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
Labels: Passed Code Review, Ready To Merge

#89 Rev-82 homepage featured listing card fix
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
Labels: Passed Code Review, Ready To Merge

#95 REV-92 agents list page sorry message when no results found
  src/assets/result-not-found-agents.svg
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/agent-list/ResultNotFound/index.jsx
  src/components/agent-list/ResultNotFound/result.styles.js
Labels: Ready For Code Review

#93 REV-96 my role page issues
  src/components/my-roles/RoleCardsContainer/data.js
  src/components/my-roles/RolesTable/roles-table.style.js
Labels: Ready For Code Review

#96 REV-89-find-an-agent-cards-duplication-and-filtration-issues
  src/assets/icons/agent-list-avatar-placeholder.svg
  src/components/agent-list/AgentCard/index.jsx
Labels: Ready For Code Review

#99 fix agent list page
  src/utils/helpers.js
Labels: Ready For Code Review

#101 fix search by type agent list
  src/assets/icons/phone-call.svg
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/hooks/use-on-screen.js
Labels: Passed Code Review, Ready To Merge

#105 REV-68-login-page-email-and-password-fields-validation-messages-are-not-appeared-FIX
  src/pages/Login/Login.jsx
Labels: Passed Code Review, Ready To Merge

#108 REV-95-my-profile-save-personal-information-validation-messages-FIX
  src/components/my-profile/MyProfileWrapper/index.jsx
Labels: Passed Code Review, Ready To Merge

#107 REV-74-login-page-and-signup-pages-auto-saved-fields-restricts-login-and-signup-procces-FIX
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review, Ready To Merge

#104 REV-93-my-profile-add-save-changes-toast-message
  src/assets/icons/toast-fail.svg
  src/assets/icons/toast-success.svg
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/Toast/index.jsx
  src/components/shared/Toast/toast.styles.js
Labels: Passed Code Review, Ready To Merge

#103 REV-100-name-does-not-get-reflected-directly-after-editing
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/contexts/UserContext/index.jsx
Labels: Passed Code Review, Ready To Merge

#109 fix phone format function
  src/utils/helpers.js
Labels: Passed Code Review, Ready To Merge

#102 REV-90 add show password into signup and login
  src/assets/eye-icon.svg
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#113 REV-93-my-profile-add-save-changes-toast-message-FIX
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/Toast/toast.styles.js
  src/hooks/use-show-toast-bar.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#112 REV-99-join-us-button-should-redirect-to-signup-page
  src/components/home/ClaimAddress/index.jsx
Labels: Passed Code Review, Ready To Merge

#116 REV-100-name-does-not-get-reflected-directly-after-editing-FIX
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/Toast/toast.styles.js
  src/contexts/UserContext/index.jsx
Labels: Comments Addressed, Passed Code Review

#120 REV-117-agent-list-enhancements
  src/assets/icons/agent-list-avatar-placeholder.svg
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
Labels: Comments Addressed, Passed Code Review

#118 REV-115-design-get-ruined-when-the-name-is-long
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up-schema.js
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review

#117 REV-111-find-an-agent-filtration-and-search-issues
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/agent-list/DesktopFilterSection/index.jsx
  src/services/user.js
Labels: Comments Addressed, Passed Code Review

#122 REV-116-sign up validation messages and other issues
  src/components/shared/FormInput/form-input.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up-schema.js
  src/pages/SignUp/sign-up.styles.js
Labels: In Code Review, Comments Addressed

#110 REV-109 search listings cards
  src/assets/close-icon.svg
  src/components/home/ExploreListing/index.jsx
  src/components/home/Storyboard/index.jsx
  src/components/home/Storyboard/storyboard.styles.js
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchList/search-list.style.js
  src/components/listing-search-page/SearchResults/index.jsx
  src/components/listing-search-page/SearchResults/listing-search-cards.style.js
  src/utils/appPaths.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#121 REV-114 lhs menu updates
  src/assets/inspection.svg
  src/components/home/Card/card.styles.js
  src/components/home/ClaimAddress/index.jsx
  src/components/home/Events/events.styles.js
  src/components/home/ExploreListing/index.jsx
  src/components/home/FeaturedListing/featured-listing.styles.js
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/ReverifiPlus/reverifi-plus.styles.js
  src/components/home/Storyboard/index.jsx
  src/components/shared/Input/input.style.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/components/shared/Sidebar/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up.styles.js
Labels: Passed Code Review, Ready To Merge

#115 REV-113 enter key not working in log in and sign up page
  src/components/shared/Button/index.jsx
  src/components/shared/FormInput/index.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review, Ready To Merge

#124 REV-124-agent-detailed-page-connect-to-backend
  src/assets/icons/agent-detailes-like.svg
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentInformation/data.js
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/AgentListings/agent-listings.style.js
  src/components/agent-details/AgentListings/index.jsx
  src/components/agent-details/AvailableServices/available-services.style.js
  src/components/agent-details/AvailableServices/data.js
  src/components/agent-details/AvailableServices/index.jsx
  src/components/agent-details/CardImage/card-image.style.js
  src/components/agent-details/CardImage/data.js
  src/components/agent-details/CardImage/index.jsx
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/CardInformation/data.js
  src/components/agent-details/CardInformation/index.jsx
  src/components/agent-details/ContactAgent/contact-agent-schema.js
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/agent-details/ContactAgent/index.jsx
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/routes.js
  src/services/listing.js
  src/services/user.js
  src/utils/helpers.js
Labels: Passed Code Review, Ready To Merge

#125 REV-130-create-how-we-work
  src/components/dashboard/DashboardWrapper/index.jsx
  src/components/how-we-work/HowWeWorkWrapper/how-we-work.styles.js
  src/components/how-we-work/HowWeWorkWrapper/index.jsx
  src/components/how-we-work/ListingsTable/index.jsx
  src/components/how-we-work/ListingsTable/listings-table.styles.js
  src/components/how-we-work/data.js
  src/components/my-roles/Roles/index.jsx
  src/components/shared/Table/index.jsx
  src/components/shared/Table/table-styles.js
  src/pages/HowWeWork.jsx
  src/routes.js
Labels: Passed Code Review, Ready To Merge

#123 REV-112-profile-page-design-and-functionalities-issues
  src/assets/add-icon-small.svg
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormInput/index.jsx
  src/components/shared/Sidebar/index.jsx
  src/contexts/UserContext/index.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review, Ready To Merge

#126 Rev 121 create listings table
  src/assets/arrow-left.svg
  src/assets/arrow-right.svg
  src/assets/delete-icon.svg
  src/assets/filter-button.svg
  src/assets/icons/schedule.svg
  src/components/create-listing/CreateListingForm/create-listing-form.styles.js
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/ListingFormMap/listing-form-map.styles.js
  src/components/dashboard/OffersTable/offers-table.styles.js
  src/components/edit-listing/Tabs/index.jsx
  src/components/edit-listing/Tabs/tabs.style.js
  src/components/listing-search-page/SearchResults/listing-search-cards.style.js
  src/components/my-listings/DeleteBox/delete-box.style.js
  src/components/my-listings/DeleteBox/index.jsx
  src/components/my-listings/ListingsHeader/index.jsx
  src/components/my-listings/ListingsHeader/listings-header.style.js
  src/components/my-listings/ListingsTable/index.jsx
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/my-listings/MyListings/index.jsx
  src/components/my-listings/MyListings/my-lsitings.style.js
  src/components/shared/Modal/index.jsx
  src/components/shared/Modal/modal.styles.js
  src/components/shared/Sidebar/index.jsx
  src/components/shared/Table/table-styles.js
  src/components/shared/Tooltip/tooltip.styles.js
  src/pages/Listing/Edit.jsx
  src/pages/MyListings.jsx
  src/routes.js
  src/services/listing.js
Labels: Passed Code Review, Ready To Merge

#127 my listing fix
  src/components/my-listings/ListingsTable/index.jsx
  src/services/listing.js
Labels: Passed Code Review, Ready To Merge

#128 fixed my listings bug
  src/components/my-listings/ListingsTable/index.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#129 Rev-114 lhs menu updates
  src/assets/menu-setting.svg
  src/assets/my-dashboard.svg
  src/assets/saved-listings.svg
  src/assets/sign-out.svg
  src/components/home/ClaimAddress/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/pages/SignUp/SignUp.jsx
Labels: Passed Code Review, Ready To Merge

#131 REV-125 homepage our featured listings images get zoomed in
  src/assets/listing-agent-image.png
  src/assets/listing-image.png
  src/components/create-listing/FormInputFields/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-page/Features/features.styles.js
  src/components/listing-page/Features/index.jsx
  src/components/listing-page/Slider/index.jsx
  src/components/my-listings/ListingsTable/index.jsx
  src/components/my-listings/ListingsTable/listing-table.style.js
  src/components/shared/FormTextArea/index.jsx
  src/pages/Listing/ListingPage.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#133 REV-124-FIX
  src/components/my-listings/ListingsTable/index.jsx
  src/contexts/UserContext/index.jsx
  src/services/listing.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#136 fix agent details page
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/CardImage/index.jsx
  src/components/agent-details/CardInformation/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#134 REV-130-FIX
  src/components/how-we-work/ListingsTable/index.jsx
  src/components/how-we-work/ListingsTable/listings-table.styles.js
Labels: Passed Code Review, Ready To Merge

#137 fix for backend
  src/components/my-listings/ListingsTable/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
  src/services/listing.js
Labels: Ready For Code Review

#138 REV-137 hide join us bannerfor logged in users
  src/components/home/ClaimAddress/index.jsx
Labels: Ready For Code Review

#140 fixed agent list
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/home/FeaturedListing/index.jsx
  src/components/shared/Tooltip/index.jsx
  src/components/shared/Tooltip/tooltip.styles.js
Labels: Ready For Code Review

#141 menu arrow fix
  src/components/shared/Sidebar/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
Labels: Ready For Code Review

#142 REV-112-fix my profile bugs
  src/assets/icons/profile-zipcode.svg
  src/components/agent-details/AgentInformation/index.jsx
  src/components/my-profile/MenuList/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper.styles.js
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormInput/index.jsx
  src/components/shared/FormTextArea/index.jsx
  src/styles/global-styles.js
  src/utils/helpers.js
Labels: Ready For Code Review

#143 REV-154-search listing updates
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/ListingSearch/listing-search.style.js
  src/components/listing-search-page/NearbyListings/index.jsx
  src/components/listing-search-page/NearbyListings/nearby-listings.style.js
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchHeader/search-header.style.js
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchList/search-list.style.js
  src/components/listing-search-page/SearchResults/index.jsx
  src/components/shared/Map/map.styles.js
Labels: Ready For Code Review

#145 REV-126-sign-up-my-profile-extension-and-phone-number-fields-accept-alphabets-and-special-characters
  src/pages/SignUp/sign-up-schema.js
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#147 fix company details update issue
  src/components/my-profile/MyProfileWrapper/index.jsx
Labels: Passed Code Review, Ready To Merge

#144 REV-145-agent-profile-bugs
  src/assets/comment.svg
  src/assets/icons/agent-detailes-like.svg
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/AgentListings/agent-listings.style.js
  src/components/agent-details/AgentListings/index.jsx
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AgentRating/index.jsx
  src/components/agent-details/CardImage/index.jsx
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/CardInformation/index.jsx
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/agent-details/ContactAgent/index.jsx
  src/components/shared/LikeButton/index.jsx
  src/components/shared/LikeButton/like-button.styles.js
Labels: Passed Code Review, Ready To Merge

#146 REV-117-fix
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
Labels: Passed Code Review, Ready To Merge

#148 REV-148 listing details page bugs
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/agent-details/ContactAgent/index.jsx
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FormInputFields/index.jsx
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-page/ContactForm/contact-form-schema.js
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/ContactForm/index.jsx
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Details/index.jsx
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/utils/helpers.js
Labels: Comments Addressed, Passed Code Review

#150 fix phone number helper function
  src/utils/helpers.js
Labels: Passed Code Review, Ready To Merge

#149 REV-147-agent-profile-enhancements
  src/assets/comment.svg
  src/assets/filled-heart.svg
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentListings/agent-listings.style.js
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/ContactAgent/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
Labels: Passed Code Review, Ready To Merge

#152 REV-158-remove-s-from-apartments-and-add-s-to-garage-back-end
  src/components/agent-details/CardInformation/index.jsx
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-page/Details/index.jsx
Labels: Passed Code Review, Ready To Merge

#155 REV-159 search listings page
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/ListingSearch/listing-search.style.js
  src/components/listing-search-page/NearbyListings/nearby-listings.style.js
  src/components/listing-search-page/SearchHeader/index.jsx
  src/components/listing-search-page/SearchHeader/search-header.style.js
  src/components/listing-search-page/SearchList/index.jsx
  src/components/listing-search-page/SearchList/search-list.style.js
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
Labels: Passed Code Review, Ready To Merge

#153 REV-151-fix-lhs-menubar
  src/components/shared/AdminPanelLayout/admin-panel-layout.styles.js
  src/components/shared/Sidebar/sidebar.styles.js
Labels: Passed Code Review, Ready To Merge

#154 REV-160-remove-ext-field-on-signup-page
  src/components/agent-details/ContactAgent/contact-agent-schema.js
  src/components/agent-details/ContactAgent/index.jsx
  src/components/create-listing/CreateListingForm/create-listing-form-schema.js
  src/components/create-listing/FormInputFields/index.jsx
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/my-profile/data.js
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up-schema.js
  src/pages/SignUp/sign-up.styles.js
Labels: Passed Code Review, Ready To Merge

#157 agent profile page fixes
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/AgentListings/agent-listings.style.js
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AgentRating/index.jsx
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/CardInformation/index.jsx
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/shared/FormTextArea/index.jsx
  src/components/shared/LikeButton/like-button.styles.js
  src/pages/SignUp/sign-up-schema.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#156 REV-148 listing fix
  src/components/create-listing/FormInputFields/index.jsx
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/overview.styles.js
  src/components/shared/FormInput/form-input.styles.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#158 REV-155-create new listing enhancemnts
  src/components/create-listing/FormInputFields/index.jsx
  src/components/shared/FormSelectInput/index.jsx
  src/components/shared/FormSelectInput/select.styles.js
Labels: Passed Code Review, Ready To Merge

#151 REV-149 listing details page enhancements
  src/components/agent-details/ContactAgent/index.jsx
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/ContactForm/index.jsx
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/listing-page/data.js
Labels: Passed Code Review, Ready To Merge

#132 REV-132-transaction-flow-step-02-manage-assign-tasks
  src/assets/icons/transaction-buyer-attorney.svg
  src/assets/icons/transaction-coordinator2.svg
  src/assets/icons/transaction-home-insurance.svg
  src/assets/icons/transaction-insurance.svg
  src/assets/icons/transaction-lender.svg
  src/assets/icons/transaction-seller-attorney.svg
  src/components/shared/Button/Button.style.js
  src/components/shared/DatePickerInput/date-picker-input.styles.js
  src/components/shared/DatePickerInput/index.jsx
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
  src/components/shared/DropdownMenu/index.jsx
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/components/shared/FormCheckbox/index.jsx
  src/components/shared/Table/index.jsx
  src/components/shared/Table/table-styles.js
  src/components/transaction/AddPartiesWrapper/add-parties-wrapper.styles.js
  src/components/transaction/AddPartiesWrapper/index.jsx
  src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper-schema.js
  src/components/transaction/AssignTasksWrapper/assign-tasks-wrapper.styles.js
  src/components/transaction/AssignTasksWrapper/index.jsx
  src/components/transaction/TransactionSharedComponent/index.jsx
  src/pages/Transaction/AddParties.jsx
  src/pages/Transaction/AssignTasks.jsx
  src/pages/Transaction/index.jsx
  src/pages/Transaction/routes.js
  src/pages/Transaction/transaction.styles.js
  src/routes.js
Labels: Passed Code Review, Ready To Merge

#159 Agent profile and my profile bugs fixes
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/CardInformation/index.jsx
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/my-profile/MyProfileWrapper/index.jsx
  src/components/my-profile/MyProfileWrapper/my-profile-wrapper-schema.js
  src/components/shared/FormInput/form-input.styles.js
  src/components/shared/FormTextArea/form-text-area.styles.js
  src/components/shared/FormTextArea/index.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#45 REV-030-add schedule component
  src/assets/images/my-listings-image.png
  src/assets/mocks/images/arrow-down.svg
  src/assets/mocks/images/arrow-up-down.svg
  src/components/edit-listing-schedule/DateInput/date-input.style.js
  src/components/edit-listing-schedule/DateInput/index.jsx
  src/components/edit-listing-schedule/ListingSchedule/days.js
  src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.js
  src/components/edit-listing-schedule/ListingSchedule/index.jsx
  src/components/edit-listing-schedule/Switch/index.jsx
  src/components/edit-listing-schedule/Switch/switch.style.js
  src/components/edit-listing-schedule/TimeInput/index.jsx
  src/components/edit-listing-schedule/TimeInput/time-input.style.js
  src/components/edit-listing/Schedule/EditListingSchedule.jsx
  src/components/edit-listing/Tabs/index.jsx
  src/components/listing-search-page/Card/index.jsx
  src/components/my-listings/ListingsTable/index.jsx
  src/components/shared/Tabs/index.jsx
  src/routes.js
  src/services/listing-create-service.js
  src/utils/appPaths.js
  src/utils/helpers.js
Labels: In Code Review, Comments Addressed

#160 REV-150-agent-profile-rate-and-review
  src/assets/icons/agent-heart.svg
  src/assets/icons/agent-list-empty-like.svg
  src/assets/icons/agent-list-like.svg
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/AgentRating/agent-rating-schema.js
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AgentRating/index.jsx
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/shared/FormTextArea/form-text-area.styles.js
  src/components/shared/FormTextArea/index.jsx
  src/components/shared/LikeButton/index.jsx
  src/services/reviews.js
Labels: Ready For Code Review

#161 REV-166 create reverifi coming soon page
  src/assets/images/reverifi-coming-soon.png
  src/components/edit-listing/ReverifiPlus/index.jsx
  src/components/edit-listing/ReverifiPlus/reverifi-plus.style.js
  src/components/edit-listing/Tabs/index.jsx
Labels: Ready For Code Review

#164 REV-164-create-listings-page-stats
  src/assets/icons/agent-heart.svg
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/shared/LikeButton/like-button.styles.js
  src/components/shared/SaveAndShareButtons/index.jsx
  src/components/shared/SaveAndShareButtons/save-and-share-buttons.styles.js
  src/pages/Listing/ListingPage.jsx
  src/services/social-statistics.js
Labels: In Code Review, Comments Addressed
