Repository OptimumPartners/reverifi, pull requests merged in 2022-01, with the labels that each got.

#19 REV-018-create-phone-verification-page
  package.json
  src/assets/icons/verify-phone-main.svg
  src/components/VerifyPhoneForm/index.jsx
  src/components/VerifyPhoneForm/verify-phone-form-schema.js
  src/components/VerifyPhoneForm/verify-phone-form.styles.js
  src/contexts/UserContext/index.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/login.styles.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/sign-up.styles.js
  src/pages/VerifyPhone/VerifyPhone.jsx
  src/pages/VerifyPhone/verify-phone.styles.js
  src/routes.js
  src/styles/colors.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Feature Review

#30 Rev-025: Implement sidebar
  src/App.jsx
  src/assets/icons/dashboard.svg
  src/assets/icons/list.svg
  src/assets/icons/logout.svg
  src/assets/icons/menu.svg
  src/assets/icons/saved.svg
  src/assets/icons/settings.svg
  src/assets/icons/transaction.svg
  src/assets/icons/user-profile.svg
  src/assets/icons/user-roles.svg
  src/components/AdminPanelLayout/admin-panel-layout.styles.js
  src/components/AdminPanelLayout/index.jsx
  src/components/Navbar/navbar.styles.js
  src/components/Sidebar/index.jsx
  src/components/Sidebar/sidebar.styles.js
  src/pages/TestSideBar.jsx
  src/routes.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Feature Review

#21 REV-023: created shared dropdown menu
  src/components/shared/Menu/index.jsx
  src/components/shared/Menu/menu.styles.js
  src/components/shared/Navbar/navbar.styles.js
  src/utils/debounce.js
  src/utils/window.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Feature Review

#34 REV-0026-Create-Map-Component
  .env.sample
  package-lock.json
  package.json
  src/assets/icons/Group-red.svg
  src/components/shared/Map/index.jsx
  src/components/shared/Map/map.styles.js
  src/components/shared/Marker/index.jsx
  src/config/config.js
Labels: In Code Review, Comments Addressed

#28 REV-026-finish shared modal and homepage modal
  src/assets/icons/dialog-close.svg
  src/assets/icons/share-listing-facebook.svg
  src/assets/icons/share-listing-main.svg
  src/assets/icons/share-listing-twitter.svg
  src/assets/icons/share-listing-whatsapp.svg
  src/components/ListingShareModal/index.jsx
  src/components/ListingShareModal/listing-share-modal-schema.js
  src/components/ListingShareModal/listing-share-modal.styles.js
  src/components/home/FeaturedListing/Card/Card.test.jsx
  src/components/home/FeaturedListing/FeaturedListing.test.jsx
  src/components/home/FeaturedListing/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/components/shared/Button/index.jsx
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/components/shared/Modal/index.jsx
  src/components/shared/Modal/modal.styles.js
  src/contexts/ShowModalContext/index.jsx
  src/pages/Home.jsx
Labels: In Code Review, Ready for QA, Comments Addressed, Needs Rebase, Ready For Feature Review

#20 REV-010: Create listing page
  src/assets/images/air-conditioner.svg
  src/assets/images/bathtub.svg
  src/assets/images/bell.svg
  src/assets/images/chevron-left.svg
  src/assets/images/chevron-right.svg
  src/assets/images/dining.svg
  src/assets/images/hair-dryer.svg
  src/assets/images/heart.svg
  src/assets/images/left-arrow.svg
  src/assets/images/location-pin.svg
  src/assets/images/location.svg
  src/assets/images/map-pin.svg
  src/assets/images/mop-water-bucket-and-cleaning-spray.svg
  src/assets/images/more-horizontal.svg
  src/assets/images/parking.svg
  src/assets/images/right-arrow.svg
  src/assets/images/rings-gym.svg
  src/assets/images/sauna.svg
  src/assets/images/share.svg
  src/assets/images/slider/abstract01.png
  src/assets/images/slider/abstract02.jpg
  src/assets/images/slider/abstract03.jpg
  src/assets/images/slider/abstract04.jpeg
  src/assets/images/swimming-pool.svg
  src/assets/images/tv.svg
  src/assets/images/wifi.svg
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Details/index.jsx
  src/components/listing-page/Features/features.styles.js
  src/components/listing-page/Features/index.jsx
  src/components/listing-page/Location/index.jsx
  src/components/listing-page/Location/location.styles.js
  src/components/listing-page/OfferDetails/index.jsx
  src/components/listing-page/OfferDetails/offer-details.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/SimilarListings/index.jsx
  src/components/listing-page/SimilarListings/similar-listings.styles.js
  src/components/listing-page/Slider/index.jsx
  src/components/listing-page/Slider/slider.styles.js
  src/components/listing-page/data.js
  src/components/shared/Button/Button.style.js
  src/index.js
  src/pages/ListingPage.jsx
  src/routes.js
Labels: Passed Code Review, Ready To Merge

#22 REV-009: create agent list page
  src/assets/icons/address.svg
  src/assets/icons/agent-heart.svg
  src/assets/icons/agent-share.svg
  src/assets/icons/filter.svg
  src/assets/icons/like.svg
  src/assets/icons/mail.svg
  src/assets/icons/phone.svg
  src/assets/icons/search.svg
  src/assets/images/demo-agent.webp
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentCardsContainer/agent-cards-container.styles.js
  src/components/agent-list/AgentCardsContainer/index.jsx
  src/components/agent-list/AgentsListBanner/agents-list-banner.styles.js
  src/components/agent-list/AgentsListBanner/index.jsx
  src/components/agent-list/DesktopFilterSection/desktop-filter-section.styles.js
  src/components/agent-list/DesktopFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/mobile-filter-section.styles.js
  src/pages/AgentList.jsx
  src/routes.js
  src/services/fake-agents-service.js
  src/styles/colors.js
Labels: Passed Code Review, Ready To Merge

#35 REV-024: create my roles page
  .eslintrc
  src/assets/icons/agent.svg
  src/assets/icons/attorney.svg
  src/assets/icons/buyer.svg
  src/assets/icons/check.svg
  src/assets/icons/edit.svg
  src/assets/icons/home-inspector.svg
  src/assets/icons/insurance-provider.svg
  src/assets/icons/lender.svg
  src/assets/icons/reverifi+.svg
  src/assets/icons/seller.svg
  src/assets/icons/transaction-coordinator.svg
  src/components/my-roles/RoleCard/index.jsx
  src/components/my-roles/RoleCard/role-card.styles.js
  src/components/my-roles/RoleCardsContainer/data.js
  src/components/my-roles/RoleCardsContainer/index.jsx
  src/components/my-roles/RoleCardsContainer/role-cards-container.styles.js
  src/components/my-roles/Roles/index.jsx
  src/components/my-roles/Roles/roles.styles.js
  src/components/my-roles/RolesTable/data.js
  src/components/my-roles/RolesTable/index.jsx
  src/components/my-roles/RolesTable/roles-table.style.js
  src/components/shared/Button/index.jsx
  src/components/shared/FormInput/index.jsx
  src/components/shared/Input/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
  src/components/verify-phone/VerifyPhoneForm/index.jsx
  src/pages/Login/Login.jsx
  src/pages/MyRoles.jsx
  src/pages/SignUp/SignUp.jsx
  src/routes.js
  src/styles/breakpoints.js
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#39 REV-029-refactor-verify-phone-page-file-structure
  src/components/shared/Sidebar/index.jsx
  src/components/shared/Sidebar/sidebar.styles.js
  src/components/verify-phone/VerifyPhoneWrapper/index.jsx
  src/components/verify-phone/VerifyPhoneWrapper/verify-phone-wrapper.styles.js
  src/pages/VerifyPhone.jsx
  src/routes.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Feature Review

#37 REV-019: Create agent details page
  src/assets/address.svg
  src/assets/agent-photo.png
  src/assets/comment.svg
  src/assets/company.svg
  src/assets/email.svg
  src/assets/filled-heart.svg
  src/assets/icons8-share.svg
  src/assets/img1.png
  src/assets/language.svg
  src/assets/like.svg
  src/assets/location.svg
  src/assets/phone.svg
  src/assets/photo-camera.svg
  src/assets/service-area.svg
  src/assets/website.svg
  src/components/agent-details/AgentInformation/agent-information.style.js
  src/components/agent-details/AgentInformation/data.js
  src/components/agent-details/AgentInformation/index.jsx
  src/components/agent-details/AgentListings/agent-listings.style.js
  src/components/agent-details/AgentListings/index.jsx
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AgentRating/index.jsx
  src/components/agent-details/AvailableServices/available-services.style.js
  src/components/agent-details/AvailableServices/data.js
  src/components/agent-details/AvailableServices/index.jsx
  src/components/agent-details/CardImage/card-image.style.js
  src/components/agent-details/CardImage/data.js
  src/components/agent-details/CardImage/index.jsx
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/CardInformation/data.js
  src/components/agent-details/CardInformation/index.jsx
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/agent-details/ContactAgent/index.jsx
  src/pages/AgentDetails.jsx
  src/pages/Home.jsx
  src/routes.js
Labels: Passed Code Review, Ready To Merge

#40 REV-028: adjust-shared-button-to-never-receive-props
  src/components/home/ClaimAddress/claim-address.styles.js
  src/components/home/ClaimAddress/index.jsx
  src/components/home/ReverifiPlus/index.jsx
  src/components/home/ReverifiPlus/reverifi-plus.styles.js
  src/components/shared/Button/Button.style.js
  src/components/shared/Button/index.jsx
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
Labels: Passed Code Review, Ready To Merge

#23 REV-013: create-listing-page-form-and-schedule-visit-component
  package-lock.json
  package.json
  src/assets/date-picker.svg
  src/assets/dial-logo.svg
  src/assets/images/user-photo.jpg
  src/assets/visit-left-arrow.svg
  src/assets/visit-right-arrow.svg
  src/components/listing-page/ContactForm/contact-form-schema.js
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/ContactForm/index.jsx
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/ScheduleVisit/data.js
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/shared/Button/index.jsx
Labels: Comments Addressed, Passed Code Review, Ready To Merge

#41 My-Roles Page Clean up
  public/index.html
  src/components/my-roles/RoleCard/index.jsx
  src/components/my-roles/RoleCard/role-card.styles.js
  src/components/my-roles/RoleCardsContainer/index.jsx
  src/components/my-roles/Roles/index.jsx
  src/components/my-roles/Roles/roles.styles.js
  src/components/my-roles/RolesTable/index.jsx
  src/components/my-roles/RolesTable/roles-table.style.js
Labels: Passed Code Review, Ready To Merge

#42 Refactor agents list page
  src/components/agent-details/AgentRating/agent-rating.style.js
  src/components/agent-details/AvailableServices/available-services.style.js
  src/components/agent-details/CardInformation/card-information.style.js
  src/components/agent-details/ContactAgent/contact-agent.style.js
  src/components/agent-list/AgentCard/agent-card.styles.js
  src/components/agent-list/AgentCard/index.jsx
  src/components/agent-list/AgentsListBanner/agents-list-banner.styles.js
  src/components/agent-list/DesktopFilterSection/desktop-filter-section.styles.js
  src/components/agent-list/DesktopFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/index.jsx
  src/components/agent-list/MobileFilterSection/mobile-filter-section.styles.js
  src/components/home/Card/card.styles.js
  src/components/home/Events/events.styles.js
  src/components/home/ExploreListing/explore-listing.styles.js
  src/components/home/FeaturedListing/featured-listing.styles.js
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/Storyboard/storyboard.styles.js
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/listing-page/SimilarListings/similar-listings.styles.js
  src/components/my-roles/RoleCard/role-card.styles.js
  src/components/shared/Button/Button.style.js
  src/components/shared/FormCheckbox/form-checkbox.style.js
  src/components/shared/Input/index.jsx
  src/components/shared/Input/input.style.js
  src/components/shared/Navbar/navbar.styles.js
  src/components/shared/Sidebar/sidebar.styles.js
  src/components/verify-phone/VerifyPhoneForm/verify-phone-form.styles.js
  src/pages/SignUp/sign-up.styles.js
  src/routes.js
  src/styles/colors.js
Labels: Ready for QA, Passed Code Review, Ready For Feature Review

#43 Refactor listing page
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/ContactForm/index.jsx
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Details/index.jsx
  src/components/listing-page/Features/features.styles.js
  src/components/listing-page/Features/index.jsx
  src/components/listing-page/Location/index.jsx
  src/components/listing-page/Location/location.styles.js
  src/components/listing-page/Offer/index.jsx
  src/components/listing-page/Offer/offer.styles.js
  src/components/listing-page/Overview/index.jsx
  src/components/listing-page/Overview/overview.styles.js
  src/components/listing-page/ScheduleVisit/data.js
  src/components/listing-page/ScheduleVisit/index.jsx
  src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
  src/components/listing-page/SimilarListings/index.jsx
  src/components/listing-page/SimilarListings/similar-listings.styles.js
  src/components/listing-page/Slider/index.jsx
  src/components/listing-page/Slider/slider.styles.js
  src/components/listing-page/data.js
  src/components/shared/Button/Button.style.js
  src/pages/Listings/ListingPage.jsx
  src/routes.js
Labels: In Code Review, Ready For Feature Review

#27 REV-017-create-listing-search-page
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/assets/icons/filter.svg
  src/assets/icons/location.svg
  src/assets/icons/search.svg
  src/assets/images/living-room.png
  src/components/listing-page/ContactForm/contact-form.styles.js
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Features/features.styles.js
  src/components/listing-page/SimilarListings/similar-listings.styles.js
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/ListingSearch/index.jsx
  src/components/listing-search-page/ListingSearch/listing-search.style.js
  src/components/listing-search-page/MapCard/index.jsx
  src/components/listing-search-page/MapCard/map-card.style.js
  src/components/listing-search-page/SearchResults/data.js
  src/components/listing-search-page/SearchResults/index.jsx
  src/components/listing-search-page/SearchResults/listing-search-cards.style.js
  src/components/shared/FormTextArea/form-text-area.styles.js
  src/components/shared/LocationSearchInput/index.jsx
  src/components/shared/LocationSearchInput/search-input.style.js
  src/components/shared/Map/index.jsx
  src/components/shared/Map/map.styles.js
  src/components/shared/Marker/index.jsx
  src/pages/ListingSearch.jsx
  src/routes.js
Labels: In Code Review, Ready for QA, Comments Addressed, Ready For Code Review, Ready For Feature Review

#48 add menu to navbar and refactor code
  src/__snapshots__/App.test.jsx.snap
  src/assets/images/notification-bell.svg
  src/components/home/ClaimAddress/__snapshots__/claim-address.test.jsx.snap
  src/components/my-roles/RoleCard/role-card.styles.js
  src/components/my-roles/RoleCardsContainer/role-cards-container.styles.js
  src/components/my-roles/Roles/roles.styles.js
  src/components/shared/Footer/__snapshots__/footer.test.jsx.snap
  src/components/shared/Input/__snapshots__/Input.test.jsx.snap
  src/components/shared/Menu/menu.styles.js
  src/components/shared/Navbar/index.jsx
  src/components/shared/Navbar/navbar.styles.js
  src/components/shared/Sidebar/sidebar.styles.js
  src/pages/Listing/Create.jsx
  src/pages/Listing/ListingPage.jsx
  src/pages/Listing/Search.jsx
  src/routes.js
Labels: Ready For Code Review

#51 Rebuild Package.json due to conflict
  .github/workflows/cicd.yml
  .gitignore
  package-lock.json
Labels: Passed Code Review, Ready To Merge

#53 Update GitHub action to handle local changes
  .github/workflows/cicd.yml
Labels: Passed Code Review, Ready To Merge

#54 Fix .vscode Addtion to .gitignore not Working
  .gitignore
  .vscode/settings.json
Labels: Ready To Merge, Ready For Code Review

#47 submitting, patching, listings form
  .eslintrc
  src/components/create-listing/CreateListingForm/create-listing-form-schema.js
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FeatureSelection/data.js
  src/components/create-listing/FeatureSelection/index.jsx
  src/components/create-listing/FormInputFields/index.jsx
  src/components/listing-page/Details/details.styles.js
  src/components/listing-page/Details/index.jsx
  src/components/listing-page/Offer/index.jsx
  src/components/shared/FormSelectInput/index.jsx
  src/pages/Listing/ListingPage.jsx
  src/routes.js
  src/services/listing-create-service.js
Labels: Passed Feature Review, Passed Code Review, Ready To Merge

#44 REV-32- finish dashboard page with shared tab, table, tooltip, accordion, dropdown menu
  docker-compose.yml
  src/assets/icons/arrow-down-white.svg
  src/assets/icons/arrow-down.svg
  src/assets/icons/dashboard-create.svg
  src/assets/icons/dashboard-dropdown-icon1.svg
  src/assets/icons/dashboard-dropdown-icon2.svg
  src/assets/icons/dashboard-money.svg
  src/assets/icons/dashboard-offers-accept.svg
  src/assets/icons/dashboard-offers-counter.svg
  src/assets/icons/dashboard-offers-decline.svg
  src/assets/icons/dashboard-people-team.svg
  src/assets/icons/transaction-summary.svg
  src/components/dashboard/DashboardWrapper/dashboard-wrapper.styles.js
  src/components/dashboard/DashboardWrapper/index.jsx
  src/components/dashboard/InvitationsTable/index.jsx
  src/components/dashboard/InvitationsTable/invitations-table.styles.js
  src/components/dashboard/OffersTable/index.jsx
  src/components/dashboard/OffersTable/offers-table.styles.js
  src/components/dashboard/TransactionsTable/index.jsx
  src/components/dashboard/TransactionsTable/transactions-table.styles.js
  src/components/dashboard/data.js
  src/components/shared/Accordion/accordion.styles.js
  src/components/shared/Accordion/index.jsx
  src/components/shared/DropdownMenu/dropdown-menu.styles.js
  src/components/shared/DropdownMenu/index.jsx
  src/components/shared/Table/index.jsx
  src/components/shared/Table/table-styles.js
  src/components/shared/Tabs/index.jsx
  src/components/shared/Tabs/tabs.styles.js
  src/components/shared/Tooltip/index.jsx
  src/components/shared/Tooltip/tooltip.styles.js
  src/pages/Dashboard.jsx
  src/routes.js
Labels: Passed Feature Review, Passed Code Review, Ready To Merge

#52 REV-38-link user roles with backend
  src/components/my-roles/RoleCard/index.jsx
  src/components/my-roles/RoleCardsContainer/data.js
  src/components/my-roles/RoleCardsContainer/index.jsx
  src/components/my-roles/Roles/index.jsx
  src/components/shared/Sidebar/index.jsx
  src/services/roles.js
  src/services/user.js
Labels: Passed Feature Review, Comments Addressed, Passed Code Review, Ready To Merge

#50 REV-036-finish get featured listings from backend
  src/components/home/FeaturedListing/data.js
  src/components/home/FeaturedListing/index.jsx
  src/components/home/FeaturedListingCard/featured-listing-card.styles.js
  src/components/home/FeaturedListingCard/index.jsx
  src/services/listing.js
  src/utils/helpers.js
Labels: Passed Feature Review, Comments Addressed, Passed Code Review, Ready To Merge

#49 REV 035 link home page with search page
  src/components/home/ExploreListing/data.js
  src/components/home/ExploreListing/explore-listing.styles.js
  src/components/home/ExploreListing/index.jsx
  src/components/home/FeaturedListing/index.jsx
  src/components/home/Storyboard/index.jsx
  src/components/listing-search-page/Card/card.style.js
  src/components/listing-search-page/Card/index.jsx
  src/components/listing-search-page/ListingSearch/listing-search.style.js
  src/components/listing-search-page/SearchResults/data.js
  src/components/listing-search-page/SearchResults/index.jsx
  src/services/listing.js
Labels: Passed Feature Review, Passed Code Review, Ready To Merge

#57 Add Jira Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready To Merge

#56 Clean-up: Listing page create form
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/create-listing/FormInputFields/index.jsx
  src/pages/Listing/ListingPage.jsx
  src/routes.js
Labels: Passed Code Review, Ready To Merge

#59 Hot-fix: Create listing Form field set
  src/components/create-listing/CreateListingForm/index.jsx
  src/components/home/FeaturedListing/index.jsx
Labels: Passed Code Review, Ready To Merge
